### ISSUE TITLE
Warnings in Speedy testing

### ISSUE THREAD

**Issue by javierggt** [sot/ska_testr#75]
The following are warnings that show up during testing of Ska3 Speedy:

- `pkg_resources is deprecated as an API` and `Deprecated call to `pkg_resources`
  - [x] ska_helpers: sot/ska_helpers/issues/55
- `'locale.getdefaultlocale' is deprecated`
  - This one comes from django (sot/skare3/issues/1245)
- `'cgi' is deprecated`
   - This one comes from django (sot/skare3/issues/1245)
- `NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays`
  - [x] chandra_aca: sot/chandra_aca/issues/166
- `AstropyDeprecationWarning: "Reader" was deprecated in version 6.0 and will be removed in a future version.`
  - [x] agasc: sot/agasc/issues/164

  - maybe others?

**Comment by jeanconn** [comment]
I'm removing the acis_thermal_check one from our list as it isn't in our control.

- `Conversion of an array with ndim > 0 to a scalar is deprecated`
  - [ ] acisops/acis_thermal_check/issues/69 -
